/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Retroblaster919 (https://sketchfab.com/Retroblaster919)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goal-ring-sonic-the-hedgehog-8f64cd10638142d692151b246d642067
Title: Goal Ring - Sonic The Hedgehog
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function GoalRing(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/goal-ring.glb')
  const { actions } = useAnimations(animations, group)
   
  useFrame((state) => {
    group.current.rotation.y += 0.003;
    group.current.position.y = -1 + Math.sin(state.clock.elapsedTime) * 0.2;

  
  });
  return (
    <group ref={group} {...props} dispose={null} scale={[1.7,1.7,1.7]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_9">
                <group name="Root_8">
                  <group name="Ring_1">
                    <group name="name1_0">
                      <mesh
                        name="Object_7"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_7.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="Star_5">
                    <group name="Star_2" rotation={[-Math.PI / 2, 0, -Math.PI]}>
                      <mesh
                        name="Object_10"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_10.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="Glow_4">
                      <group name="circle_3" rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                          name="Object_13"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_13.geometry}
                          material={materials.material_2}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="Segmented_part_7">
                    <group name="tube_6" rotation={[-Math.PI / 2, -0.175, 0]}>
                      <mesh
                        name="Object_16"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_16.geometry}
                        material={materials.material_3}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/goal-ring.glb')